apiVersion: v1
data:
  application.properties: |2-

    # Configuration for the incoming cloud events received by the serverless workflows.
    mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
    mp.messaging.incoming.kogito_incoming_stream.path=/
    mp.messaging.incoming.kogito_incoming_stream.method=POST

    # This property is used when sending the notification while waiting for Q&A
    move2kube_url=${MOVE2KUBE_URL:http://move2kube-svc.default.svc.cluster.local:8080}
    # This property is used to send requests to the move2kube instance
    quarkus.rest-client.move2kube_yaml.url=${MOVE2KUBE_URL:http://move2kube-svc.default.svc.cluster.local:8080}
    # This property is used to send requests to the backstage notification plugin
    quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://backstage-backstage.rhdh-operator}
    quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: m2k
    sonataflow.org/workflow-app: m2k
  name: m2k-props
