apiVersion: v2
name: workflows
description: A Helm chart for serverless workflows
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 0.2.24

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: greeting
    repository: "file://../greeting"
    version: "0.2.9"
    condition: greeting.enabled
  - name: move2kube
    repository: "file://../move2kube"
    version: "0.2.14"
    condition: move2kube.enabled
  - name: mta
    repository: "file://../mta"
    version: "0.2.15"
    condition: mta.enabled

icon: https://raw.githubusercontent.com/parodos-dev/parodos-dev.github.io/main/assets/images/WO_black.svg
