mta:
  enabled: true # Indicates that mta workflow is enabled
greeting:
  enabled: true # Indicates that greeting workflow is enabled
move2kube:
  enabled: false # Indicates that move2kube workflow is enabled
